-- Création des tables stations et distances
CREATE TABLE stations (
    id SERIAL PRIMARY KEY,
    shortName VARCHAR(5) UNIQUE NOT NULL,
    longName VARCHAR(255) NOT NULL
);

CREATE TABLE distances (
    transport_name VARCHAR(10) NOT NULL,
    fk_parent_stations VARCHAR(5) NOT NULL,
    fk_child_stations VARCHAR(5) NOT NULL,
    distance FLOAT NOT NULL,

    CONSTRAINT fk_parent FOREIGN KEY (fk_parent_stations)
        REFERENCES stations(shortName),

    CONSTRAINT fk_child FOREIGN KEY (fk_child_stations)
        REFERENCES stations(shortName)
);

CREATE TABLE anayltics_routes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_station_id VARCHAR(5) NOT NULL REFERENCES stations(shortName),
    to_station_id VARCHAR(5) NOT NULL REFERENCES stations(shortName),
    analytic_code VARCHAR(255) NOT NULL,
    distance_km FLOAT NOT NULL,
    path TEXT[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insertion des données
INSERT INTO stations (id, shortName, longName) VALUES
    (1, 'ALLI', 'Allières'),
    (2, 'AVA', 'Les Avants'),
    (3, 'BCHX', 'Bois-de-Chexbres'),
    (4, 'BEMM', 'Belmont-sur-Mx'),
    (5, 'BLB', 'Blankenburg'),
    (6, 'BLON', 'Blonay'),
    (7, 'BODE', 'Boden'),
    (8, 'CABY', 'Chamby'),
    (9, 'CASE', 'Les Cases'),
    (10, 'CAUX', 'Caux'),
    (11, 'CGE', 'Montreux-Collège'),
    (12, 'CHAL', 'Châtelard VD'),
    (13, 'CHAN', 'Chantemerle-près-Blonay'),
    (14, 'CHAU', 'La Chaudanne-Les Moulins'),
    (15, 'CHBL', 'Château-de-Blonay'),
    (16, 'CHCO', 'Chaulin-Cornaux'),
    (17, 'CHER', 'Chernex'),
    (18, 'CHEV', 'Les Chevalleyres'),
    (19, 'CHIZ', 'La Chiésaz'),
    (20, 'CHOE', 'Château-d''Oex'),
    (21, 'CHTV', 'Château-d''Hauteville'),
    (22, 'CLIE', 'Clies'),
    (23, 'COLD', 'Colondalles'),
    (24, 'COMS', 'Les Combes'),
    (25, 'CRDB', 'Crêt-d''y-Bau'),
    (26, 'ECTS', 'Les Echets'),
    (27, 'FAY', 'Fayaux'),
    (28, 'FLED', 'Flendruz'),
    (29, 'FON', 'Fontanivent'),
    (30, 'VVVI', 'Vevey Vignerons'),
    (31, 'GLCO', 'Glion-Collège'),
    (32, 'GLI', 'Glion'),
    (33, 'GLIA', 'Glion-Alpes'),
    (34, 'GRAC', 'Château-d''Oex-Les Granges'),
    (35, 'GRUB', 'Gruben'),
    (36, 'GST', 'Gstaad'),
    (37, 'HALN', 'Halten'),
    (38, 'HDC', 'Haut-de-Caux'),
    (39, 'HTV', 'Hauteville'),
    (40, 'JAMA', 'Jaman'),
    (41, 'JOR', 'Jor'),
    (42, 'LAL', 'Lally'),
    (43, 'LENK', 'Lenk im Simmental'),
    (44, 'MATE', 'Matten'),
    (45, 'MTB', 'Montbovon'),
    (46, 'MX', 'Montreux'),
    (47, 'OES', 'Oeschseite'),
    (48, 'OEYA', 'Anschussgl. Oey'),
    (49, 'OND', 'Ondallaz-L''Alliaz'),
    (50, 'PACC', 'Paccot'),
    (51, 'PALZ', 'La Palaz'),
    (52, 'PERC', 'La Perche'),
    (53, 'PLAC', 'Planchamp'),
    (54, 'PLCH', 'Les Planches'),
    (55, 'PLEI', 'Les Pléiades'),
    (56, 'PRLN', 'Prélaz-sur-Blonay'),
    (57, 'RODN', 'Rochers-de-Naye'),
    (58, 'ROSI', 'Rossinière'),
    (59, 'ROU', 'Rougemont'),
    (60, 'SAAN', 'Saanen'),
    (61, 'SAMO', 'Saanenmöser'),
    (62, 'SCI', 'Les Sciernes'),
    (63, 'SCR', 'Schönried'),
    (64, 'SDY', 'Sendy-Sollard'),
    (65, 'SONZ', 'Sonzier'),
    (66, 'STLE', 'St-Légier-Gare'),
    (67, 'STLV', 'St-Légier-Village'),
    (68, 'STOI', 'Stöckli'),
    (69, 'STST', 'St. Stephan'),
    (70, 'TINE', 'La Tine'),
    (71, 'TOV', 'Toveyre'),
    (72, 'TREM', 'Le Tremblex'),
    (73, 'TUS', 'Tusinge'),
    (74, 'VALM', 'Valmont'),
    (75, 'VUAR', 'Vuarennes'),
    (76, 'VV', 'Vevey'),
    (77, 'ZW', 'Zweisimmen'),
    (78, 'BOSQ', 'Bosquets'),
    (86, 'GRU', 'Grubenwald'),
    (87, 'WBA', 'Weissenbach'),
    (88, 'BOLT', 'Boltigen'),
    (89, 'ENGE', 'Enge im Simmental'),
    (90, 'OIS', 'Oberwil im Simmental'),
    (91, 'WG', 'Weissenburg'),
    (92, 'DR', 'Därstetten'),
    (93, 'RGD', 'Ringoldingen'),
    (94, 'ERLB', 'Erlenbach im Simmental'),
    (95, 'OE', 'Oey-Diemtigen'),
    (96, 'BH', 'Burgholz'),
    (97, 'WM', 'Wimmis'),
    (98, 'EIF', 'Eifeld'),
    (99, 'LAT', 'Lattigen bei Spiez'),
    (100, 'SPAB', 'Spiez (Abzw)'),
    (101, 'SP', 'Spiez'),
    (102, 'FS', 'Faulensee'),
    (103, 'KH', 'Krattighalde'),
    (104, 'LBAD', 'Leissigbad (Agl)'),
    (105, 'LSS', 'Leissigen'),
    (106, 'DAE', 'Därligen'),
    (107, 'IW', 'Interlaken West'),
    (108, 'IO', 'Interlaken Ost');


INSERT INTO distances (transport_name, fk_parent_stations, fk_child_stations, distance) VALUES
    ('MOB','MX','CGE',0.65),
    ('MOB','CGE','VUAR',0.35),
    ('MOB','VUAR','BEMM',0.51),
    ('MOB','BEMM','COLD',0.24),
    ('MOB','COLD','CHAL',0.4),
    ('MOB','CHAL','PLAC',0.51),
    ('MOB','PLAC','FON',0.62),
    ('MOB','FON','CHER',1.01),
    ('MOB','CHER','SONZ',1.18),
    ('MOB','SONZ','CABY',1.68),
    ('MOB','CABY','SDY',2.05),
    ('MOB','SDY','AVA',1.65),
    ('MOB','AVA','JOR',1.78),
    ('MOB','JOR','CASE',2.56),
    ('MOB','CASE','ALLI',1.78),
    ('MOB','ALLI','SCI',3.46),
    ('MOB','SCI','MTB',1.71),
    ('MOB','MTB','TINE',1.95),
    ('MOB','TINE','ROSI',4.14),
    ('MOB','ROSI','CHAU',1.15),
    ('MOB','CHAU','CHOE',3.29),
    ('MOB','CHOE','PALZ',1),
    ('MOB','PALZ','GRAC',0.87),
    ('MOB','GRAC','COMS',1.59),
    ('MOB','COMS','FLED',1.28),
    ('MOB','FLED','ROU',1.91),
    ('MOB','ROU','SAAN',4.04),
    ('MOB','SAAN','GST',2.4),
    ('MOB','GST','GRUB',2.51),
    ('MOB','GRUB','SCR',2.58),
    ('MOB','SCR','SAMO',2.21),
    ('MOB','SAMO','OES',3.83),
    ('MOB','OES','HALN',2.64),
    ('MOB','HALN','ZW',2.9),
    ('MOB','ZW','BLB',1.65),
    ('MOB','BLB','STOI',2.89),
    ('MOB','STOI','STST',1.78),
    ('MOB','STST','MATE',2.17),
    ('MOB','MATE','BODE',2.82),
    ('MOB','BODE','LENK',1.55),
    ('MOB','ZW','GRU',3.08),
    ('MOB','GRU','WBA',2.94),
    ('MOB','WBA','BOLT',2.98),
    ('MOB','BOLT','ENGE',3.28),
    ('MOB','ENGE','OIS',1.73),
    ('MOB','OIS','WG',3.25),
    ('MOB','WG','DR',1.54),
    ('MOB','DR','RGD',2.31),
    ('MOB','RGD','ERLB',2.5),
    ('MOB','ERLB','OE',1.96),
    ('MOB','OE','BH',2.18),
    ('MOB','BH','WM',2.61),
    ('MOB','WM','EIF',1.05),
    ('MOB','EIF','LAT',1.04),
    ('MOB','LAT','SPAB',1.57),
    ('MOB','SPAB','SP',0.89),
    ('MOB','SP','FS',2.02),
    ('MOB','FS','KH',3.44),
    ('MOB','KH','LBAD',1.3),
    ('MOB','LBAD','LSS',1.79),
    ('MOB','LSS','DAE',3.52),
    ('MOB','DAE','IW',4.01),
    ('MOB','IW','IO',1.93),
    ('MVR-ce', 'BLON','CHAN',0.97),
    ('MVR-ce', 'CHAN','CHCO',1.02),
    ('MVR-ce', 'CHCO','CABY',0.96),
    ('MVR-ce', 'VV','BOSQ',0.53),
    ('MVR-ce', 'BOSQ','VVVI',0.97),
    ('MVR-ce', 'VVVI','CLIE',0.27),
    ('MVR-ce', 'CLIE','HTV',0.69),
    ('MVR-ce', 'HTV','CHTV',0.56),
    ('MVR-ce', 'CHTV','STLE',0.58),
    ('MVR-ce', 'STLE','STLV',0.42),
    ('MVR-ce', 'STLV','CHIZ',0.49),
    ('MVR-ce', 'CHIZ','CHBL',0.84),
    ('MVR-ce', 'CHBL','BLON',0.37),
    ('MVR-ce', 'BLON','PRLN',0.45),
    ('MVR-ce', 'PRLN','TUS',0.77),
    ('MVR-ce', 'TUS','CHEV',0.41),
    ('MVR-ce', 'CHEV','BCHX',0.36),
    ('MVR-ce', 'BCHX','FAY',0.72),
    ('MVR-ce', 'FAY','OND',0.74),
    ('MVR-ce', 'OND','LAL',0.64),
    ('MVR-ce', 'LAL','PLEI',0.7);